--공지게시판테이블 생성
CREATE TABLE GONGGIBOARD(
 GBOARD_SEQ   NUMBER(10)  primary key,
 GBOARD_GROUP VARCHAR2(10), 
 GBOARD_SUBJECT VARCHAR2(255),
 GBOARD_WRITER  VARCHAR2(100),
 GBOARD_CONTENTS VARCHAR2(4000),
 GBOARD_DATE     TIMESTAMP(6)
);

DROP TABLE GONGGIBOARD;

CREATE sequence gboard_seq;
DROP SEQUENCE gboard_seq;